# Generated by Django 4.2 on 2023-04-26 11:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                ("guid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="CouponCodeCreate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("guid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="EventDate",
            fields=[
                ("guid", models.AutoField(primary_key=True, serialize=False)),
                ("start", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="EventLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "capacity",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9999999999),
                        ]
                    ),
                ),
                ("address", models.CharField(max_length=65536)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OAuthClient",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("secret", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.CharField(max_length=100)),
                ("updated_at", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Organizer",
            fields=[
                ("guid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=280)),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                ("guid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("oder_id", models.AutoField(primary_key=True, serialize=False)),
                ("shop_name", models.CharField(max_length=255)),
                ("event_name", models.CharField(max_length=255)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("ticket_name", models.CharField(max_length=255)),
                ("order_status", models.CharField(max_length=15)),
                ("device", models.CharField(max_length=15)),
                ("order_metadata_city", models.CharField(max_length=15)),
                (
                    "order_metadata_age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(120),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wrap",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EventixApp.organizer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("guid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "event_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EventixApp.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CouponCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=4)),
                ("used_count", models.IntegerField()),
                (
                    "coupon_guid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EventixApp.coupon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("context", models.JSONField(default=list)),
                (
                    "wrap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EventixApp.wrap",
                    ),
                ),
            ],
        ),
    ]
