# Generated by Django 4.2 on 2023-05-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EventixApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="name",
            field=models.CharField(default=None, max_length=250),
        ),
    ]
