# Generated by Django 4.2 on 2023-05-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EventixApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wrap",
            old_name="owner",
            new_name="owner_account_id",
        ),
    ]
