# Generated by Django 4.2 on 2023-06-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EventixApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="context",
            field=models.CharField(max_length=2500),
        ),
    ]
