# Generated by Django 4.2 on 2023-06-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EventixApp", "0002_alter_card_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="wrap",
            name="organizer_name",
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
