version: '3'
services:
  my_service:
    build:
      context: EventixPrj
      dockerfile: Dockerfile
  backend-eventix:
    image: s1t2e3f4an/django-app:0.0.1
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=neondb
      - DB_USER=tepa.popescu
      - DB_PASSWORD=EZ9IYnarR7Od
      - DB_PORT=5432
    volumes:
      - .:/code
  db:
    image: postgres
    environment:
      - POSTGRES_DB=neondb
      - POSTGRES_USER=tepa.popescu
      - POSTGRES_PASSWORD=EZ9IYnarR7Od
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
